### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by vitaly-t**
This is how to do this properly, and without async.

### CODE REVIEW

**Comment by yamstr** [comment]
@vitaly-t, thanks

**Comment by vitaly-t** [comment]
Пожалуйста! :)

**Comment by yamstr** [comment]
Your recommendations added - https://github.com/yamstr/naprirodku.ru/commit/5a4c0d6fc4677ba55e950c765c1a04015d187743

**Comment by vitaly-t** [comment]
@yamstr you are welcome!

And if you are willing to use ES6 syntax, such code example can get much simpler. Let me know, if you interested - I'll show how exactly ;)

**Comment by vitaly-t** [comment]
Anyway, while I had a moment... :)

``` js
app.get('/articles/:id/', function (req, res, next) {
    db.task(function *(t) {
            let article = yield t.one('SELECT * FROM articles WHERE id = $1', req.params.id);
            let position = yield t.one('SELECT *, position[0] AS lat, position[1] AS lng FROM places WHERE id = $1', article.place_id);
            return {article, position};
        })
        .then(function (data) {
            data.article.body = marked(data.article.body);
            let p = data.place;
            p.position = {lat: p.lat, lng: p.lng};
            res.render('article', data);
        })
        .catch(function (error) {
            next();
        });
});
```

**Comment by yamstr** [comment]
Thank you! Code with generators is more readable and compact.

**Pull request closed without merging**
